### ISSUE TITLE
Recent astyle release is not available

### ISSUE THREAD

**Issue by nlohmann** [Freed-Wu/astyle-wheel#18]
pypi offers version 3.4.13, whereas https://sourceforge.net/projects/astyle/files/astyle/ offers version 3.5 and 3.6.

**Comment by Freed-Wu** [comment]
That is because upstream's bug: https://gitlab.com/saalen/astyle/-/issues/51

https://github.com/pypa/cibuildwheel use a docker image to build wheel. the OS of docker image is almalinux 9, which is a fork of old CentOS. gcc of this OS is very old. old gcc use default `-std=c++11`, latest gcc use a higher C++ standard.
the upstream use C++17, however, don't declare `-std=c++17`, which make `cibuildwheel` failed.

**Comment by Freed-Wu** [comment]
3.4.13 is the last version to use C++11. now latest 3.6.6 still forget add `-std=c++17`:

```
/opt/rh/devtoolset-10/root/usr/bin/g++  -pthread -DASTYLE_LIB -D__init___EXPORTS -I/tmp/tmpjdjubkg8/build -I/project -I/tmp/tmpjdjubkg8/build/_deps/astyle-src/AStyle/src -isystem /opt/python/cp310-cp310/include/python3.10 -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/__init__.dir/src/astyle/wrap.cc.o -MF CMakeFiles/__init__.dir/src/astyle/wrap.cc.o.d -o CMakeFiles/__init__.dir/src/astyle/wrap.cc.o -c /project/src/astyle/wrap.cc
```

**Comment by Freed-Wu** [comment]
Will fix in 3.6.6

**Comment by Freed-Wu** [comment]
Download https://pypi.org/project/astyle/#files

**Comment by nlohmann** [comment]
Thanks a lot, and happy new year!
